
package itmedical;
import BD.CitasDAO;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class NuevaCitaDialog extends javax.swing.JDialog {
    private Sistema sistemaPadre;
    private String estudioSeleccionado;
    
   public NuevaCitaDialog(Sistema sistemaPadre, boolean modal, String estudio)  {
    super(sistemaPadre, modal);
    this.sistemaPadre = sistemaPadre;
    this.estudioSeleccionado = estudio;
    initComponents();
    
    ComboBoxEstudio.setModel(new javax.swing.DefaultComboBoxModel<>(
    new String[] {
        "Hombro derecho",
        "Hombro izquierdo",
        "Brazo derecho",
        "Brazo izquierdo",
        "Codo derecho",
        "Codo izquierdo",
        "Muñeca derecha",
        "Muñeca izquierda",
        "Columna cervical",
        "Columna dorsal",
        "Columna lumbar",
        "Cadera derecha",
        "Cadera izquierda",
        "Rodilla derecha",
        "Rodilla izquierda",
        "Tobillo derecho",
        "Tobillo izquierdo",
        "Pie derecho",
        "Pie izquierdo",
        "Espalda completa"
    }
));
ComboBoxObraSocial1.setModel(new javax.swing.DefaultComboBoxModel<>(
    new String[] {
        "Particular",
        "OSDE",
        "Swiss Medical",
        "Galeno",
        "Medicus",
        "Sancor Salud",
        "OMINT",
        "IOMA",
        "PAMI",
        "OSPRERA"
    }
));


    this.estudioSeleccionado = estudio;

    

    ComboBoxEstudio.setSelectedItem(estudio);
}
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textRecepPor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textHora1 = new javax.swing.JTextField();
        textPacientes = new javax.swing.JTextField();
        textDni = new javax.swing.JTextField();
        textImporte = new javax.swing.JTextField();
        textObservaciones = new javax.swing.JTextField();
        textContacto = new javax.swing.JTextField();
        textDadoPor = new javax.swing.JTextField();
        ComboBoxEstudio = new javax.swing.JComboBox<>();
        ComboBoxObraSocial1 = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JPanel();
        labelReiniciar = new javax.swing.JLabel();
        btnAgregar1 = new javax.swing.JPanel();
        labelAgregar1 = new javax.swing.JLabel();
        labelAgregar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contacto:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 20));

        jLabel2.setFont(new java.awt.Font("Roboto SemiCondensed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FORMULARIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, -1));

        textRecepPor.setBackground(new java.awt.Color(204, 204, 204));
        textRecepPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRecepPorActionPerformed(evt);
            }
        });
        jPanel1.add(textRecepPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 170, -1));

        jLabel3.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hora:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, 20));

        jLabel4.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pacientes:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 20));

        jLabel5.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DNI:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 40, 20));

        jLabel6.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Estudio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 20));

        jLabel7.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Obra Social:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 90, 20));

        jLabel8.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Recepcionado Por:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, 20));

        jLabel9.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Dado Por:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, 20));

        jLabel10.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Observaciones:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 100, 20));

        jLabel11.setFont(new java.awt.Font("Roboto SemiCondensed", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Importe:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 20));

        textHora1.setBackground(new java.awt.Color(204, 204, 204));
        textHora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHora1ActionPerformed(evt);
            }
        });
        jPanel1.add(textHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 250, -1));

        textPacientes.setBackground(new java.awt.Color(204, 204, 204));
        textPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPacientesActionPerformed(evt);
            }
        });
        jPanel1.add(textPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 220, -1));

        textDni.setBackground(new java.awt.Color(204, 204, 204));
        textDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDniActionPerformed(evt);
            }
        });
        jPanel1.add(textDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, -1));

        textImporte.setBackground(new java.awt.Color(204, 204, 204));
        textImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textImporteActionPerformed(evt);
            }
        });
        jPanel1.add(textImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 220, -1));

        textObservaciones.setBackground(new java.awt.Color(204, 204, 204));
        textObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textObservacionesActionPerformed(evt);
            }
        });
        jPanel1.add(textObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 210, -1));

        textContacto.setBackground(new java.awt.Color(204, 204, 204));
        textContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContactoActionPerformed(evt);
            }
        });
        jPanel1.add(textContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 220, -1));

        textDadoPor.setBackground(new java.awt.Color(204, 204, 204));
        textDadoPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDadoPorActionPerformed(evt);
            }
        });
        jPanel1.add(textDadoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 230, -1));

        ComboBoxEstudio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ComboBoxEstudio.setModel(new javax.swing.DefaultComboBoxModel<>(     new String[] {         \"Hombro derecho\"", "\"Hombro izquierdo\"", "\"Brazo derecho\"", "\"Brazo izquierdo\"", "\"Codo derecho\"", "\"Codo izquierdo\"", "\"Muñeca derecha\"", "\"Muñeca izquierda\"", "\"Columna cervical\"", "\"Columna dorsal\"", "\"Columna lumbar\"", "\"Cadera derecha\"", "\"Cadera izquierda\"", "\"Rodilla derecha\"", "\"Rodilla izquierda\"", "\"Tobillo derecho\"", "\"Tobillo izquierdo\"", "\"Pie derecho\"", "\"Pie izquierdo\"", "\"Espalda completa\"     } ));" }));
        ComboBoxEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEstudioActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBoxEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, -1));

        ComboBoxObraSocial1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxObraSocial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxObraSocial1ActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBoxObraSocial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 220, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        labelReiniciar.setBackground(new java.awt.Color(255, 255, 255));
        labelReiniciar.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 0, 14)); // NOI18N
        labelReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        labelReiniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReiniciar.setText("Cancelar");
        labelReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCancelarLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(labelReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCancelarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 110, -1));

        btnAgregar1.setBackground(new java.awt.Color(0, 157, 217));
        btnAgregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregar1MouseExited(evt);
            }
        });

        labelAgregar1.setBackground(new java.awt.Color(255, 255, 255));
        labelAgregar1.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 0, 14)); // NOI18N
        labelAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        labelAgregar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAgregar1.setText("Agregar");
        labelAgregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnAgregar1Layout = new javax.swing.GroupLayout(btnAgregar1);
        btnAgregar1.setLayout(btnAgregar1Layout);
        btnAgregar1Layout.setHorizontalGroup(
            btnAgregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnAgregar1Layout.setVerticalGroup(
            btnAgregar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 110, -1));

        labelAgregar.setBackground(new java.awt.Color(255, 255, 255));
        labelAgregar.setFont(new java.awt.Font("Roboto SemiCondensed SemiBold", 0, 14)); // NOI18N
        labelAgregar.setForeground(new java.awt.Color(255, 255, 255));
        labelAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAgregar.setText("Agregar");
        labelAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(labelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 86, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textRecepPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRecepPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRecepPorActionPerformed

    private void textHora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHora1ActionPerformed

    private void textPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPacientesActionPerformed

    private void textDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDniActionPerformed

    private void textImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textImporteActionPerformed

    private void textObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textObservacionesActionPerformed

    private void textContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContactoActionPerformed

    private void textDadoPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDadoPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDadoPorActionPerformed

    private void ComboBoxEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxEstudioActionPerformed

    private void ComboBoxObraSocial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxObraSocial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxObraSocial1ActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnAgregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar1MouseClicked
        if (textPacientes.getText().trim().isEmpty() ||
        textHora1.getText().trim().isEmpty() ||
        textDni.getText().trim().isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(this,
            "Paciente, Hora y DNI son obligatorios");
        return;
    }

    // por ahora solo validamos
    javax.swing.JOptionPane.showMessageDialog(this,
        "Validación correcta (después guardamos en BD)");
    
    CitasDAO dao = new CitasDAO();

    boolean ok = dao.insertarCita(
    textHora1.getText(),
    textPacientes.getText(),
    textDni.getText(),
    estudioSeleccionado, // ✅ ACÁ ESTÁ LA CLAVE
    ComboBoxObraSocial1.getSelectedItem().toString(),
    textImporte.getText(),
    textContacto.getText(),
    textObservaciones.getText(),
    textDadoPor.getText(),
    textRecepPor.getText()
);


if (ok) {
    JOptionPane.showMessageDialog(this, "Cita guardada correctamente");
    sistemaPadre.refrescarTablas();
    dispose(); // cierra el diálogo
} else {
    JOptionPane.showMessageDialog(this, "Error al guardar la cita");
}
    }//GEN-LAST:event_btnAgregar1MouseClicked

    private void btnAgregar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar1MouseEntered

    private void btnAgregar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaCitaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaCitaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaCitaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaCitaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxEstudio;
    private javax.swing.JComboBox<String> ComboBoxObraSocial1;
    private javax.swing.JPanel btnAgregar1;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAgregar;
    private javax.swing.JLabel labelAgregar1;
    private javax.swing.JLabel labelReiniciar;
    private javax.swing.JTextField textContacto;
    private javax.swing.JTextField textDadoPor;
    private javax.swing.JTextField textDni;
    private javax.swing.JTextField textHora1;
    private javax.swing.JTextField textImporte;
    private javax.swing.JTextField textObservaciones;
    private javax.swing.JTextField textPacientes;
    private javax.swing.JTextField textRecepPor;
    // End of variables declaration//GEN-END:variables
}